spring:
  application:
    name: task2
  webflux:
    base-path: /api

server:
  port: 8080

external-api:
  url: https://services-api.ryanair.com
  connectTimeout: 5000 # in milliseconds
  responseTimeout: 1000 # in milliseconds

cache:
    expiration: 30 # in minutes
    maxSize: 100